package org.kettoo.app

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.RectangleShape
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.font.FontWeight
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.File
import java.util.UUID

private fun age(at:Long):String{val m=((System.currentTimeMillis()-at)/60000).coerceAtLeast(0);return if(m<1)"just now" else if(m<60)"${m}m ago" else "${m/60}h ago"}
@Composable fun PhaseLocation(app:KettooApplication){val ops by app.operations.state.collectAsStateWithLifecycle();var open by remember{mutableStateOf(false)};var floor by remember{mutableStateOf("")};val d=ops.snapshot ?: return;val check=d.optJSONObject("checkin")
 TextButton({open=true},Modifier.fillMaxWidth()){Icon(Icons.Outlined.LocationOn,null);Text(check?.optString("zone_name") ?: "My location · unknown");if(check!=null)Text(" · "+age(check.getLong("reported_at")),fontSize=10.sp)}
 if(open)AlertDialog(onDismissRequest={open=false},title={Text("My location")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Select your floor and zone. Your communication team stays the same.",fontSize=12.sp);d.getJSONArray("floors").objects().forEach{f->OutlinedButton({floor=f.getString("id")},Modifier.fillMaxWidth(),shape=RectangleShape){Text(f.getString("name")+(if(floor==f.getString("id"))" ✓" else ""))}};d.getJSONArray("zones").objects().filter{it.getString("floor_id")==floor}.forEach{z->Button({app.run{app.operations.checkin(z.getString("id"))};open=false},Modifier.fillMaxWidth(),shape=RectangleShape){Text(z.getString("name"))}};if(!ops.live)Text("Update will be queued until the server reconnects.",fontSize=12.sp)}},confirmButton={TextButton({open=false}){Text("Close")}})
}
@Composable fun PhaseComms(app:KettooApplication){val ops by app.operations.state.collectAsStateWithLifecycle();val s by app.state.collectAsStateWithLifecycle();val d=ops.snapshot ?: return;val team=d.optJSONObject("team");val admin=d.optJSONObject("dutyAdmin");val e=d.optJSONObject("exchange")
 Column(Modifier.fillMaxWidth().background(Color.White).padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("TEAM · ${team?.optString("name") ?: "Unassigned"}",fontSize=11.sp,fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){if(team!=null)OutlinedButton({app.select(team.getString("channel_id"))},Modifier.weight(1f),shape=RectangleShape){Text("Team PTT",fontSize=12.sp)};if(e==null)OutlinedButton({app.run{app.operations.talkAdmin()}},Modifier.weight(1f),enabled=ops.live&&s.duty&&admin?.optBoolean("reachable")==true,shape=RectangleShape){Text(if(admin?.optBoolean("busy")==true)"Admin busy" else "Talk to admin",fontSize=12.sp)}else OutlinedButton({app.select(e.getString("conversation_id"))},Modifier.weight(1f),shape=RectangleShape){Text("Private admin PTT",fontSize=12.sp)}};if(e!=null)TextButton({app.run{app.operations.endExchange()}}){Text("End private exchange",fontSize=11.sp)};Text("Duty admin: ${admin?.optString("name") ?: "Not designated"} · ${if(admin?.optBoolean("reachable")==true)"available" else "unavailable"}",fontSize=10.sp,color=Color.DarkGray)}
}
@Composable private fun PhaseImage(app:KettooApplication,id:String){val ops by app.operations.state.collectAsStateWithLifecycle();val bitmap by produceState<Bitmap?>(null,id,ops.live){value=runCatching{val file=app.operations.image(id);withContext(Dispatchers.IO){val bounds=BitmapFactory.Options().apply{inJustDecodeBounds=true};BitmapFactory.decodeFile(file.absolutePath,bounds);val options=BitmapFactory.Options().apply{inSampleSize=(bounds.outWidth/1200).coerceAtLeast(1)};BitmapFactory.decodeFile(file.absolutePath,options)}}.getOrNull()};bitmap?.let{Image(it.asImageBitmap(),"Issue photo",Modifier.fillMaxWidth().heightIn(max=300.dp))}}
@Composable fun ThreadsScreen(app:KettooApplication){val ops by app.operations.state.collectAsStateWithLifecycle();val session by app.state.collectAsStateWithLifecycle();val d=ops.snapshot;var filter by remember{mutableStateOf("open")};var create by remember{mutableStateOf(false)};var detail by remember{mutableStateOf<JSONObject?>(null)}
 fun open(id:String){app.run{detail=app.operations.thread(id)}}
 LaunchedEffect(d?.optLong("serverAt")){detail?.let{t->if(d?.getJSONArray("issues")?.objects()?.none{it.getString("id")==t.getString("id")}==true)detail=null else if(ops.live)app.run{detail=app.operations.thread(t.getString("id"))}}}
 LazyColumn(Modifier.fillMaxSize().padding(horizontal=20.dp),verticalArrangement=Arrangement.spacedBy(12.dp),contentPadding=PaddingValues(vertical=18.dp)){
 item{Text("Follow through.",fontSize=28.sp,fontWeight=FontWeight.Bold);Text(if(ops.live)"SERVER SYNCHRONISED" else "CACHED · SERVER UNAVAILABLE",fontSize=10.sp,color=if(ops.live)Color(0xFF31755B)else Color(0xFF936319));d?.let{Text("Last update "+age(it.getLong("serverAt")),fontSize=10.sp)}}
 item{Button({create=true},Modifier.fillMaxWidth(),enabled=d!=null,shape=RectangleShape){Icon(Icons.Outlined.Add,null);Text("New thread")}}
 item{Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("open" to "Open","team" to "My team","mine" to "Assigned to me","all" to "All history").forEach{(k,label)->OutlinedButton({filter=k},shape=RectangleShape,colors=ButtonDefaults.outlinedButtonColors(containerColor=if(filter==k)Color.Black else Color.White,contentColor=if(filter==k)Color.White else Color.Black)){Text(label,fontSize=11.sp)}}}}
 val list=d?.getJSONArray("issues")?.objects()?.filter{x->when(filter){"open"->x.getString("status")!="resolved";"team"->x.optString("team_id")==d.optJSONObject("team")?.optString("id");"mine"->x.optString("owner_id")==session.user?.getString("id");else->true}} ?: emptyList()
 items(list,key={it.getString("id")}){x->Column(Modifier.fillMaxWidth().border(1.dp,Color.LightGray).background(Color.White).clickable{open(x.getString("id"))}.padding(15.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Priority(x.getString("priority"));Text(x.getString("title"),fontSize=17.sp,fontWeight=FontWeight.Bold);Text("${x.getString("status").replace('_',' ')} · ${x.optString("owner_name").takeUnless{it=="null"||it.isBlank()} ?: "Unassigned"}",fontSize=11.sp);Text("${x.optString("zone_name").takeUnless{it=="null"||it.isBlank()} ?: "No zone"} · ${if(x.getString("audience")=="team")"Team only" else "Everyone"} · ${age(x.getLong("updated_at"))}",fontSize=10.sp,color=Color.DarkGray)}}
 if(list.isEmpty())item{Text(if(d==null)"Connect to the organisation server to load threads." else "No issues match this filter.",fontSize=13.sp,color=Color.Gray)}
 if(ops.pending.isNotEmpty())item{Text("LOCAL UPDATES",fontSize=11.sp,fontWeight=FontWeight.Bold)}
 items(ops.pending,key={it.id}){o->Column(Modifier.background(Color(0xFFFFF5E2)).padding(13.dp)){Text("${JSONObject(o.body).optString("title").ifBlank{if(o.path=="/checkins")"Location check-in" else "Reply"}} · ${o.state}",fontSize=12.sp);Text(o.error.ifBlank{"Awaiting server confirmation"},fontSize=10.sp);if(o.state=="rejected")TextButton({app.run{app.operations.dismiss(o.id)}}){Text("Dismiss rejected update")}}}
 }
 if(create&&d!=null)CreateThread(app,d){create=false}
 if(detail!=null)ThreadDetail(app,detail!!,{detail=null}){detail=it}
}
@Composable private fun Priority(value:String){val bg=when(value){"urgent"->Color(0xFFFFE6E1);"high"->Color(0xFFFFF0D3);else->Color(0xFFF0F0EF)};Text(value.uppercase(),Modifier.background(bg).padding(horizontal=8.dp,vertical=5.dp),fontSize=10.sp,fontWeight=FontWeight.Bold)}
@Composable private fun CreateThread(app:KettooApplication,d:JSONObject,close:()->Unit){var title by remember{mutableStateOf("")};var description by remember{mutableStateOf("")};var priority by remember{mutableStateOf("normal")};var audience by remember{mutableStateOf("team")};var zone by remember{mutableStateOf(d.optJSONObject("checkin")?.optString("zone_id") ?: "")};var photo by remember{mutableStateOf<File?>(null)};var mime by remember{mutableStateOf("")};var saving by remember{mutableStateOf(false)}
 val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri:Uri?->if(uri!=null)app.run{val type=app.contentResolver.getType(uri) ?: error("Unknown image format");check(type in listOf("image/png","image/jpeg","image/webp")){"Use PNG, JPEG or WebP"};val file=File(app.filesDir,"attachments/${UUID.randomUUID()}.image");withContext(Dispatchers.IO){try{app.contentResolver.openInputStream(uri)!!.use{input->file.outputStream().use{out->val b=ByteArray(8192);var total=0;while(true){val n=input.read(b);if(n<0)break;total+=n;check(total<=5*1024*1024){"Photo limit is 5 MB"};out.write(b,0,n)}}}}catch(e:Exception){file.delete();throw e}};photo=file;mime=type}}
 AlertDialog(onDismissRequest=close,title={Text("Report an issue")},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(12.dp)){OutlinedTextField(title,{title=it.take(120)},label={Text("Title")},shape=RectangleShape);OutlinedTextField(description,{description=it.take(4000)},label={Text("Description")},minLines=3,shape=RectangleShape);DictateButton(app,"issue-description",description){description=it};Text("Priority",fontSize=12.sp);Row{listOf("normal","high","urgent").forEach{v->TextButton({priority=v}){Text(v+(if(priority==v)" ✓"else ""),fontSize=11.sp)}}};Text("Audience",fontSize=12.sp);Row{TextButton({audience="team"}){Text("My team"+(if(audience=="team")" ✓"else ""))};TextButton({audience="everyone"}){Text("Everyone"+(if(audience=="everyone")" ✓"else ""))}};Text("Zone (optional)",fontSize=12.sp);TextButton({zone=""}){Text("No zone"+(if(zone.isBlank())" ✓"else ""))};d.getJSONArray("zones").objects().forEach{z->TextButton({zone=z.getString("id")}){val floor=d.getJSONArray("floors").objects().find{it.getString("id")==z.getString("floor_id")};Text("${floor?.optString("name")} / ${z.getString("name")}"+(if(zone==z.getString("id"))" ✓"else ""),fontSize=11.sp)}};OutlinedButton({picker.launch(arrayOf("image/png","image/jpeg","image/webp"))},shape=RectangleShape){Text(if(photo!=null)"Photo attached · change" else "Add photo (optional)")};Text("Offline reports queue for the server. Priority does not interrupt audio.",fontSize=10.sp)}},confirmButton={TextButton({saving=true;app.run{try{val body=json("id" to UUID.randomUUID().toString(),"title" to title.trim(),"description" to description.trim(),"priority" to priority,"audience" to audience,"teamId" to d.optJSONObject("team")?.optString("id"),"zoneId" to zone.ifBlank{null},"createdAt" to System.currentTimeMillis());app.operations.queue("/threads",body,photo,mime);close()}finally{saving=false}}},enabled=!saving&&title.isNotBlank()&&description.isNotBlank()&&(audience!="team"||d.optJSONObject("team")!=null)){Text("Create thread")}},dismissButton={TextButton(close){Text("Cancel")}})
}
@Composable private fun ThreadDetail(app:KettooApplication,t:JSONObject,close:()->Unit,update:(JSONObject)->Unit){val ops by app.operations.state.collectAsStateWithLifecycle();val s by app.state.collectAsStateWithLifecycle();var reply by remember{mutableStateOf("")};var acting by remember{mutableStateOf(false)};val iid=t.getString("id");val uid=s.user?.optString("id");val admin=s.user?.optString("role")=="admin";var reassign by remember{mutableStateOf(false)}
 fun action(name:String,owner:String?=null){acting=true;app.run{try{app.api.objectCall("/threads/$iid/$name",json("version" to t.getInt("version"),"ownerId" to owner));app.operations.refresh();update(app.operations.thread(iid))}finally{acting=false}}}
 AlertDialog(onDismissRequest=close,title={Text(t.getString("title"))},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(12.dp)){Priority(t.getString("priority"));Text("${t.getString("status").replace('_',' ')} · ${t.optString("owner_name").takeUnless{it=="null"||it.isBlank()} ?: "Unassigned"}",fontSize=12.sp);Text(t.getString("description"),fontSize=14.sp);t.optString("photo_id").takeUnless{it=="null"||it.isBlank()}?.let{PhaseImage(app,it)};Text("${t.optString("zone_name").takeUnless{it=="null"||it.isBlank()} ?: "No zone"} · ${if(t.getString("audience")=="team")"Team only" else "Everyone"}",fontSize=10.sp);
 if(t.getString("status")=="open")Button({action("claim")},enabled=ops.live&&!acting,shape=RectangleShape){Text("I'll handle this")}
 if(t.getString("status")!="resolved"&&(admin||uid==t.getString("author_id")||uid==t.optString("owner_id")))OutlinedButton({action("resolve")},enabled=ops.live&&!acting,shape=RectangleShape){Text("Mark resolved")}
 if(admin){OutlinedButton({action("reopen")},enabled=ops.live&&!acting,shape=RectangleShape){Text("Reopen")};TextButton({reassign=!reassign},enabled=ops.live&&!acting){Text("Reassign")};if(reassign)ops.snapshot?.getJSONArray("volunteers")?.objects()?.filter{t.getString("audience")=="everyone"||it.optJSONObject("team")?.optString("id")==t.optString("team_id")}?.forEach{u->TextButton({action("reassign",u.getString("id"));reassign=false}){Text(u.getString("name"))}}}
 Text("Ownership and status require server confirmation.",fontSize=10.sp,color=Color.Gray);HorizontalDivider();Text("Follow-ups",fontWeight=FontWeight.Bold);t.getJSONArray("replies").objects().forEach{r->Column(Modifier.fillMaxWidth().background(Color(0xFFF4F4F2)).padding(12.dp)){Text(r.getString("author_name")+" · "+age(r.getLong("created_at")),fontSize=10.sp,fontWeight=FontWeight.Bold);Text(r.getString("text"),fontSize=13.sp)}};OutlinedTextField(reply,{reply=it.take(4000)},label={Text("Progress update")},minLines=2,shape=RectangleShape);DictateButton(app,"reply:$iid",reply){reply=it};Button({app.run{app.operations.queue("/threads/$iid/replies",json("id" to UUID.randomUUID().toString(),"text" to reply.trim(),"createdAt" to System.currentTimeMillis()));reply="";if(ops.live)update(app.operations.thread(iid))}},enabled=reply.isNotBlank(),shape=RectangleShape){Text("Post reply")};if(!ops.live)Text("Cached view. Replies queue until reconnect.",fontSize=11.sp)}},confirmButton={TextButton(close){Text("Close")}})
}
